version: "2"

services:
  web:
    build: .
    environment:
      - VIRTUAL_HOST=10.0.0.70
      - VIRTUAL_PORT=8080
    depends_on:
      - redis
      - nginx-proxy

  redis:
    image: redis

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

